// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: file_transfer.proto

#include "file_transfer.pb.h"
#include "file_transfer.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace filetransfer {

static const char* FileTransfer_method_names[] = {
  "/filetransfer.FileTransfer/Upload",
  "/filetransfer.FileTransfer/Download",
};

std::unique_ptr< FileTransfer::Stub> FileTransfer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< FileTransfer::Stub> stub(new FileTransfer::Stub(channel, options));
  return stub;
}

FileTransfer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Upload_(FileTransfer_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  , rpcmethod_Download_(FileTransfer_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::ClientWriter< ::filetransfer::FileChunk>* FileTransfer::Stub::UploadRaw(::grpc::ClientContext* context, ::filetransfer::TransferStatus* response) {
  return ::grpc::internal::ClientWriterFactory< ::filetransfer::FileChunk>::Create(channel_.get(), rpcmethod_Upload_, context, response);
}

void FileTransfer::Stub::async::Upload(::grpc::ClientContext* context, ::filetransfer::TransferStatus* response, ::grpc::ClientWriteReactor< ::filetransfer::FileChunk>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::filetransfer::FileChunk>::Create(stub_->channel_.get(), stub_->rpcmethod_Upload_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::filetransfer::FileChunk>* FileTransfer::Stub::AsyncUploadRaw(::grpc::ClientContext* context, ::filetransfer::TransferStatus* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::filetransfer::FileChunk>::Create(channel_.get(), cq, rpcmethod_Upload_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::filetransfer::FileChunk>* FileTransfer::Stub::PrepareAsyncUploadRaw(::grpc::ClientContext* context, ::filetransfer::TransferStatus* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::filetransfer::FileChunk>::Create(channel_.get(), cq, rpcmethod_Upload_, context, response, false, nullptr);
}

::grpc::ClientReader< ::filetransfer::FileChunk>* FileTransfer::Stub::DownloadRaw(::grpc::ClientContext* context, const ::filetransfer::FileRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::filetransfer::FileChunk>::Create(channel_.get(), rpcmethod_Download_, context, request);
}

void FileTransfer::Stub::async::Download(::grpc::ClientContext* context, const ::filetransfer::FileRequest* request, ::grpc::ClientReadReactor< ::filetransfer::FileChunk>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::filetransfer::FileChunk>::Create(stub_->channel_.get(), stub_->rpcmethod_Download_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::filetransfer::FileChunk>* FileTransfer::Stub::AsyncDownloadRaw(::grpc::ClientContext* context, const ::filetransfer::FileRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::filetransfer::FileChunk>::Create(channel_.get(), cq, rpcmethod_Download_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::filetransfer::FileChunk>* FileTransfer::Stub::PrepareAsyncDownloadRaw(::grpc::ClientContext* context, const ::filetransfer::FileRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::filetransfer::FileChunk>::Create(channel_.get(), cq, rpcmethod_Download_, context, request, false, nullptr);
}

FileTransfer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileTransfer_method_names[0],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< FileTransfer::Service, ::filetransfer::FileChunk, ::filetransfer::TransferStatus>(
          [](FileTransfer::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::filetransfer::FileChunk>* reader,
             ::filetransfer::TransferStatus* resp) {
               return service->Upload(ctx, reader, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileTransfer_method_names[1],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< FileTransfer::Service, ::filetransfer::FileRequest, ::filetransfer::FileChunk>(
          [](FileTransfer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::filetransfer::FileRequest* req,
             ::grpc::ServerWriter<::filetransfer::FileChunk>* writer) {
               return service->Download(ctx, req, writer);
             }, this)));
}

FileTransfer::Service::~Service() {
}

::grpc::Status FileTransfer::Service::Upload(::grpc::ServerContext* context, ::grpc::ServerReader< ::filetransfer::FileChunk>* reader, ::filetransfer::TransferStatus* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileTransfer::Service::Download(::grpc::ServerContext* context, const ::filetransfer::FileRequest* request, ::grpc::ServerWriter< ::filetransfer::FileChunk>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace filetransfer

